// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdUGz3d70D2jHiwDZEQH1OjSPOlubeyZE',
    appId: '1:382766602802:android:e5bc04b6bd34f5eb76fa2b',
    messagingSenderId: '382766602802',
    projectId: 'goandgo-ade9b',
    authDomain: 'aub-pickusup.firebaseapp.com',
    storageBucket: 'goandgo-ade9b.appspot.com',
    measurementId: 'G-VLY053XQ4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFRtC7kL4a8T6zgzSgq0FdiirclIQPl1o',
    appId: '1:382766602802:android:e5bc04b6bd34f5eb76fa2b',
    messagingSenderId: '382766602802',
    projectId: 'goandgo-ade9b',
    storageBucket: 'goandgo-ade9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf3QY51xh4IG-jlkhlthtIwOa8v9Xfa68',
    appId: '1:382766602802:android:e5bc04b6bd34f5eb76fa2b',
    messagingSenderId: '382766602802',
    projectId: 'goandgo-ade9b',
    storageBucket: 'goandgo-ade9b.appspot.com',
    iosClientId:
        '645186470981-5nofdlrotprplr9h8qdkdrfuo36i85k8.apps.googleusercontent.com',
    iosBundleId: 'com.powerrangers.goandgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf3QY51xh4IG-jlkhlthtIwOa8v9Xfa68',
    appId: '1:382766602802:android:e5bc04b6bd34f5eb76fa2b',
    messagingSenderId: '382766602802',
    projectId: 'goandgo-ade9b',
    storageBucket: 'goandgo-ade9b.appspot.com',
    iosClientId:
        '645186470981-5nofdlrotprplr9h8qdkdrfuo36i85k8.apps.googleusercontent.com',
    iosBundleId: 'com.powerrangers.goandgo',
  );
}
